language: generic

env:
  matrix:
    - JULIA_VERSION=1.0
    - JULIA_VERSION=1.1
    - JULIA_VERSION=nightly

matrix:
  allow_failures:
    - env: JULIA_VERSION=nightly

services:
  - docker

script:
  - bin/runtests

notifications:
  email: false
